version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DB_HOST: db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_COMPLETIONS: ${OPENAI_API_COMPLETIONS}
      OPENAI_API_RESPONSES: ${OPENAI_API_RESPONSES}
      OPENAI_API_MODEL: ${OPENAI_API_MODEL}
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    container_name: chatbot-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      retries: 5

  test-runner:
    build:
      context: .
      dockerfile: tests/Dockerfile.test
    depends_on:
      - app
    environment:
      APPLICATION_URL: http://app:3000
    entrypoint: []
    volumes:
    - ./tests/reports:/app/tests/reports