# Dockerfile.tests
FROM python:3.11-slim

WORKDIR /app

COPY tests/security ./tests/security
COPY tests/performance ./tests/performance
COPY tests/api ./tests/api

# Install dependencies
RUN pip install --no-cache-dir pytest requests responses presidio-analyzer locust python-dotenv

CMD ["pytest"]  # Default, überschreibbar